#!/bin/csh -x

switch ($1) 

case help:
  ./export_wordpress.py -h
  breaksw
 
case dtis:
  ./export_wordpress.py \
    -u root \
    -f work/pass \
    -t webservices \
    -x webservices \
    -v 2.6 \
    -c blog_post \
    -a 'http://www.lib.umd.edu/blogs/webservices/wp-content/uploads' \
  > work/dtis/nodes-pre.xml \
  && ../webharvest/bin/groovy fixnodes work/dtis/nodes-pre.xml > work/dtis/nodes.xml \
  && xslt -x ../webharvest/conf/report.xsl -i work/dtis/nodes.xml list=true full=true
  breaksw

case ocpg:
  ./export_wordpress.py --username=root \
    --passfile='work/pass' \
    --table=ocpg \
    --prefix=ocpg \
    --version=2.0 \
    --content=blog_post \
    --attachments='http://www.lib.umd.edu/blogs/ocpg/wp-content/uploads' \
    --debug \
  > work/ocpg/nodes-pre.xml \
  && ../webharvest/bin/groovy fixnodes work/ocpg/nodes-pre.xml > work/ocpg/nodes.xml \
  && xslt -x ../webharvest/conf/report.xsl -i work/ocpg/nodes.xml list=true full=true
  breaksw

case sst:
  ./export_wordpress.py --username=root \
    --passfile='work/pass' \
    --table=sst \
    --prefix=sst \
    --version=2.0 \
    --content=page \
    --attachments='http://www.lib.umd.edu/blogs/sst/wp-content/uploads' \
    --debug \
  > work/sst/nodes-pre.xml \
  && ../webharvest/bin/groovy fixnodes work/sst/nodes-pre.xml > work/sst/nodes.xml \
  && xslt -x ../webharvest/conf/report.xsl -i work/sst/nodes.xml list=true full=true
  breaksw

default:
  echo invalid option
  breaksw
endsw
